# editDB


### Ожидаемок поведение:

#### main.py в Кейсе 1
*Комментируем все кейсы, кроме первого*

При вызове функции

    add_customer('123') 

из блока "with" (т.е. при наличии 4 пробелов в начале названия функции) создается строка в базе и сохраняется, после чего проверяется отображается в выводе с помощью функции 

    show_all_rows()

При этом с каждым новым запуском скрипта main.py создается новая строка в бд, изменения сохраняются.
Вывод после двух вызовов такой:

    [(None, '123', None), (None, '123', None)]

#### main.py в Кейсе 2
*Комментируем все кейсы, кроме второго*

Если вызывать функцию add_customer('321') без пробелов в начале, изменения сохраняются в базу и  этом отображаются в show_all_rows()

С каждым новым запуском скрипта вывод НЕ совпадает с предыдущим.
Первый запуск:

    [(None, '321', None)]

Второй запуск:

    [(None, '321', None), (None, '321', None)]

#### caller.py в Кейсе 3
*Комментируем все кейсы, кроме третьего*

Ожидаемый вывод при первом запуске caller.py и пустой бд:

    [(None, '999', None)]

При втором:

    [(None, '999', None), (None, '999', None)]


### Фактическое поведение:

Кейс 1 работает правильно, как и ожидадется.

Кейс 2.

Если вызывать функцию add_customer('321') без пробелов в начале, изменения не сохраняются в базу, но при этом отображаются в show_all_rows()

С каждым новым запуском скрипта main.py вывод совпадает с предыдущим:

    [(None, '321', None)]

Второй запуск:

    [(None, '321', None)]
Кейс работает НЕ правильно.

Кейс 3.

При запуске caller.py пустой бд вывод (как первый, так и последующие) также пустой:

    []

При этом если в main.py расскоментирован "Кейс 2", то вывод (как первый, так и последующие) копируют поведение, описанное в фактическом поведении скрипта main.py, т.е создают одну строку, показывают ее, но не сохраняют.

Первый вывод:

    [(None, '321', None)]

Второй:

    [(None, '321', None)]
